name: NPM Publish

on:
  push:
    tags:
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest
#     env:
#       NODE_AUTH_TOKEN: ${{secrets.npm_token}}

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: "https://registry.npmjs.org/:_authToken=${{secrets.npm_token}}"
    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
    - name: Setup Version
      run: |
        npm version $RELEASE_VERSION --no-git-tag
    - name: Push to NPM (alpha)
      if: "contains(github.ref, 'alpha')"
      run: npm publish --access public --tag alpha
#       env:
#         NODE_AUTH_TOKEN: ${{secrets.npm_token}}
    - name: Push to NPM (beta)
      if: "contains(github.ref, 'beta')"
      run: npm publish --access public --tag beta
#       env:
#         NODE_AUTH_TOKEN: ${{secrets.npm_token}}
    - name: Push to NPM
      if: "!contains(github.ref, 'alpha') && !contains(github.ref, 'beta')"
      run: npm publish --access public
#       env:
#         NODE_AUTH_TOKEN: ${{secrets.npm_token}}
